### PR TITLE
Added support for custom collections in configuration and accompanying tests

### LINKED ISSUE #163: Custom collection support
There appears to be no support for custom collections, including, but not limited to: configuration support and command line generation support.

### PR DESCRIPTION
**Pull request by Bilge**
This builds on #164 so you might want to merge that first so the diff doesn't look so muddy. Alternatively just review [the relevant commit](https://github.com/doctrine/DoctrineMongoODMModule/pull/166/commits/198c141baa5632485debfbd36ab44adb4d0ebc2b).

This closes #163.

### CODE REVIEW

**Comment by alcaeus** [comment]
@Bilge: sorry for the long delay here. Could you rebase the branch and resolve conflicts? Thanks!

**Comment by Bilge** [comment]
At some point it becomes unreasonable to request the original author to continue making changes. Having already redone most of my PRs at least once, only to have them closed 9 months later, if you're really serious about merging this time the responsibility to resolve conflicts arising due to negligence should fall on the maintainers.

**Comment by alcaeus** [comment]
Fair enough.

**Comment by Bilge** [comment]
@alcaeus Your disdain and absolute lack of respect for my work is duly noted.

**Comment by alcaeus** [comment]
FWIW, I asked if you could rebase the branch because without a rebase (and conflict resolution) I can't merge this PR. If you feel that it is unreasonable for me to ask that, you leave me no choice but to close the PR and cherry-pick the commits when I have the time to do so.

I know that this (and other PRs) have been sitting around idle for quite some time. Now that I (and @malarzm) are maintainers of this repository and have push access, we can only try to play the catch-up game, which can be sped up with the help of contributors.

**Comment by Bilge** [comment]
Sorry, I thought by closing this PR you intended to ditch my commits. If you plan to cherry-pick them that's another matter entirely, but if that is the case, I urge you to reopen this PR.

I hope you understand that, given the last time I was asked to do this, and despite tending to it immediately; since my PR was subsequently ignored for further 6 months I am reluctant to do it again. That said, I understand yourself and @malarzm are probably better maintainers, so I may yet find time to revisit this, but again, in that case I urge you to reopen the PR until such a time as someone merges it so the commits are not forgotten.

**Comment by alcaeus** [comment]
Very well, I'm reopening it. Please let me know if you've found time to revisit it so I can merge it before it requires yet another rebase. Alternatively, I'll just cherry-pick commit 198c141 since #175 changes array syntax and 5.5 has been dropped from master already.

**Comment by Bilge** [comment]
@alcaeus I can try to work on this but I need #165 as well. Please reopen it.

**Comment by Bilge** [comment]
@alcaeus I have painstakingly gone through and resolved all conflicts. However, there is a strange test error to do with logging that I don't know how to resolve.

**Comment by alcaeus** [comment]
I'll take a look at the tests later this week, I'll have to dive into the code to see what's supposed to be going on.

As for #165, I've [commented](https://github.com/doctrine/DoctrineMongoODMModule/pull/165#issuecomment-279200658) that the generator command might as well be added to this PR since it's one block.

Please also remove the refactorings (short array syntax) from this PR since #175 takes care of that. I'm holding off merging refactorings like that until the current feature PRs are merged to spare everyone the expensive rebases.

**Comment by Bilge** [comment]
@alcaeus It would be a lot of work to remove the short array syntax refactoring. I originally presented the array syntax fix, the other PR is the duplicate, so if either should be modified it should be the duplicate. However, it does not seem necessary to remove such refactoring since they both make the same changes so they should not conflict.

I can try to merge the closed PR into this one but it will bloat this PR somewhat.

I greatly appreciate your support on the testing issue.

**Comment by alcaeus** [comment]
You are making things unnecessarily complicated by having commits in multiple PRs. Your short array refactoring was in #164, #165 and #166. It doesn't belong in the latter two, since those are feature PRs and I don't want to mix features with refactorings to make merging features easier and require less rebases. I hope you understand.

**Comment by Bilge** [comment]
That is because I started with refactoring in order to build features on top of the refactoring. There was not supposed to be any difficulty or delay in getting the refactoring merged, and having done so, the diff for the features would naturally become clean. All of these problems stemmed from the fact that my PRs never got merged, which in turn, made my features look messy. Now I am made to suffer for that effort.

**Comment by alcaeus** [comment]
Superseded by #181. Thanks for your efforts, @Bilge!

**Pull request closed without merging**
