### PR TITLE
Feature: Laminas support and PHP 7.2+ only

### LINKED ISSUE #210: Transition to Laminas
Now Zend made it's transition to Laminas the package need to be updated to point to the correct new packages.

### PR DESCRIPTION
**Pull request by michalbundyra**
Fixes #210

### CODE REVIEW

**Comment by alcaeus** [comment]
The module is in need of serious work to support ODM 2.0. Given the low number of installs, I'm wondering if this is worth the necessary work.

**Comment by michalbundyra** [comment]
@alcaeus Ofc. But I can't do everything in one PR ;-) And we have to start from something. This was fairly easy and I think it is a good start point for next major.

**Comment by alcaeus** [comment]
Don't worry, I wasn't trying to imply that it needs to be done in one PR. Since ODM 1.1 officially supports PHP 5.6 and PHP 7 is only supported through an adapter library due to the MongoDB driver switch, we should make the module compatible with ODM 2.0 first before bumping the PHP dependency to 7.2.

**Comment by TomHAnderson** [comment]
Merged to `develop`  There is still more work to do.  As long as we haven't pulled the plug on this project then I see the next steps to make it compatible with Laminas.  I have a personal desire to see this continue to support the laminas-api-tools doctrine integration.

**Pull request closed without merging**
