### PR TITLE
#165 just CLI command: generate persistent-collections

### PR DESCRIPTION
**Pull request by webimpress**
/cc @gianarb @Bilge

### CODE REVIEW

**Comment by gianarb** [comment]
Missing tests and duplicated https://github.com/doctrine/DoctrineMongoODMModule/pull/165

but thanks @webimpress

**Comment by webimpress** [comment]
@gianarb there IS a test ;) The same as for others CLI commands.

I know it's duplicated, as you can see in PR subject, just cleared #165 PR to add just a CLI command, as cooperation on it with the author of #165 is not working. It's fine to me if you want for update on original PR 👍

**Comment by gianarb** [comment]
You are right. Just give me some time to understand what we can do with the original one. it's not a good practice submit PR already claimed and we have not pressure about this feature

**Comment by webimpress** [comment]
Agreed, thanks @gianarb 👍

**Pull request closed without merging**
