### PR TITLE
Set up CI/CD using Github actions

### PR DESCRIPTION
**Pull request by driehle**
After Travis has been shut down, this repository has not been migrated to Github actions yet. This PR sets up CI and CD using Github actions. Workflows re-use the organization workflows where possible.

Some minor changes in the test configuration were required to allow the tests passing in Github CI as well as locally in the `docker-compose` environment. I am not sure if we want to keep that docker-compose setup (we have it nowhere else), but I could be nice for first-time contributers as it allows to run tests locally much easier. Therefore, I don't see much sense in putting effort into removing it.

Besides, the `.gitignore` and `.gitattributes` was synchronized with the other Laminas-related repositories and the common `FUNDING.yml` was added.

(Note: Badges still refering to Travis are already updated in #230, hence those changes don't appear here.)

### CODE REVIEW

**Review by greg0ire — APPROVED** [review]
Should we mark any of the jobs here as required in the settings?

**Review by TomHAnderson — CHANGES_REQUESTED** [review]
docker-compose.yml

```
- PHP_VERSION=${PHP_VERSION:-7.2}
```

should be changed to 

```
- PHP_VERSION=${PHP_VERSION:-7.4}
```

Because 7.2 is untestable now.

**Comment by driehle** [comment]
@greg0ire
> Should we mark any of the jobs here as required in the settings?

Not sure what this means... 🤔

@TomHAnderson
> Because 7.2 is untestable now.

Why is this untestable? Installing PHP 7.2 via Docker still works fine. And PHP 7.2 currently still is our lowest supported PHP version. I used docker-compose locally and did not have any issues with it.

**Comment by greg0ire** [comment]
@driehle I mean this: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-protected-branches#require-status-checks-before-merging

**Comment by TomHAnderson** [comment]
```
[Pro@~/Projects/doctrine/doctrine-mongo-odm-module (feature/remove-travis-use-github-actions)]$ docker-compose run --rm php composer test
Creating doctrine-mongo-odm-module_mongodb_1 ... done
Creating doctrine-mongo-odm-module_php_run   ... done
Running composer test
> phpunit --colors=always --stop-on-error

Fatal error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 7.4.0". You are running 7.2.34. in /docker/vendor/composer/platform_check.php on line 24
Script phpunit --colors=always --stop-on-error handling the test event returned with error code 255
ERROR: 255
```

**Comment by driehle** [comment]
Rebased

**Review by TomHAnderson — APPROVED** [review]
Regarding my earlier composer error, that was user error.

**Pull request merged**
