### PR TITLE
Fixed PHPUnit warnings in PHP >= 5.6

### PR DESCRIPTION
**Pull request by Bilge**
This builds on #164 so you might want to merge that first so the diff doesn't look so muddy. Alternatively just review [the relevant commit](https://github.com/doctrine/DoctrineMongoODMModule/commit/68a77499fd3baae560092e45a9432e0fafc94337).

### CODE REVIEW

**Comment by webimpress** [comment]
@Bilge sorry, what warning you get? You can check last travis build and all seems to be fine.
It will be nice to use short array syntax, I'd go also with trailing commas at the end of multiline arrays. I'm not sure about changing `$this->` to `self::` in tests (I know that it's correct, but commonly used is `$this->`, also in PHPUnit documentation).

**Comment by Bilge** [comment]
`getMock` is deprecated.

**Comment by webimpress** [comment]
@Bilge yes, it is [since PHPUnit 5.4](https://github.com/sebastianbergmann/phpunit/blob/5.5/ChangeLog-5.4.md#changed-2). As you can see library required [PHPUnit 4.8](https://github.com/doctrine/DoctrineMongoODMModule/blob/master/composer.json#L54) so at this moment all is good.

**Comment by Bilge** [comment]
@webimpress It is deprecated in the 4.x branch.

**Comment by webimpress** [comment]
@Bilge Please have a look:
4.8: https://github.com/sebastianbergmann/phpunit/blob/4.8/src/Framework/TestCase.php#L1312-L1335
5.4: https://github.com/sebastianbergmann/phpunit/blob/5.4/src/Framework/TestCase.php#L1557

**Comment by Bilge** [comment]
I would not have changed it if it wasn't necessary.

**Comment by webimpress** [comment]
> I would not have changed it if it wasn't necessary.

@Bilge Please check above resources and than re-thing if your change was necessary.

BTW. From Zend conduct:
> **To err is human.** You might not intend it, but mistakes do happen and
   contribute to build experience. Tolerate honest mistakes, and don't hesitate
   to apologize if you make one yourself.

I think all libraries should contain this ...

**Comment by Bilge** [comment]
@webimpress  Please get out of my PRs your commentary is unwelcome.

**Comment by gianarb** [comment]
Hello @Bilge , you are always too polite!

We have to take a common street across modules for this feature. I close this PR right know and I will come back soon on your work with a cherry-pick if we decide to take this street.

**Comment by Bilge** [comment]
@gianarb I fail to see what difficulty you have in making a decision here. Short array syntax is available since PHP 5.4, for the past 4.5 years, and the minimum supported version has already moved on to 5.6. It should be an easy decision for anyone to make.

**Pull request closed without merging**
