### PR TITLE
Add DoctrineObject factory for DocumentManager

### PR DESCRIPTION
**Pull request by fabiocarneiro**
This allows to use the MongoDB DocumentManager as DoctrineObject hydrator default object manager, by switching module positions in zf2 app config, or removes the necessity of creating a factory for it or setting the object manager in a fieldset.

### CODE REVIEW

**Comment by fabiocarneiro** [comment]
@gianarb Will i have to update this for 5.4- compatibility? or will it be increased like ORM?

**Comment by gianarb** [comment]
Hi @fabiocarneiro thanks for your contribution!
We are discussion about this stuff in this moment.. :)
There are a lot of developers that use php 5.3 :)

**Comment by fabiocarneiro** [comment]
@gianarb php 5.3 is not installing anymore. doctrine/doctrine-module 0.9.x-dev requires php >=5.4

**Comment by gianarb** [comment]
Oh yes :) Thanks!

**Comment by gianarb** [comment]
Merge b4fffeb

**Pull request closed without merging**
