### PR TITLE
Support for `odm:schema:update` command

### PR DESCRIPTION
**Pull request by vbarinov**
Support for `odm:schema:update` command

### CODE REVIEW

**Comment by Ocramius** [comment]
@gianarb I think a test is missing here

**Comment by vbarinov** [comment]
@Ocramius I added the necessary test

**Comment by Ocramius** [comment]
Looks good :+1:

**Comment by gianarb** [comment]
:+1:

**Comment by Ocramius** [comment]
@vbarinov thanks!

**Pull request merged**
