### PR TITLE
allow adding custom types via module config

### PR DESCRIPTION
**Pull request by prolic**

### CODE REVIEW

**Comment by gianarb** [comment]
Thanks for this feature.. have you time to add a few tests? :+1:

**Comment by prolic** [comment]
There are not tests at all currently for that factory, even in the ORM Module. So with this in mind, I really like to write some tests for this! ;-)

Stay tuned....

**Comment by gianarb** [comment]
Thanks for your important test improvement! :+1:

**Comment by prolic** [comment]
So I hope this is enough for this time!

Haf phun! :+1:

**Comment by gianarb** [comment]
Beautiful! :)

**Pull request merged**
