### PR TITLE
Allows null value as DefaultDb

### PR DESCRIPTION
**Pull request by neilime**

### CODE REVIEW

**Comment by gianarb** [comment]
Hi! Use case please
Why this feature?

**Comment by neilime** [comment]
The connection factory allows `null` value for default db (https://github.com/doctrine/DoctrineMongoODMModule/blob/master/src/DoctrineMongoODMModule/Service/ConnectionFactory.php#L83), so we should be able to set default bd to `null`

**Comment by gianarb** [comment]
@neilime can you apply CS Fix and can you added a test? Thanks

**Comment by gianarb** [comment]
Thanks and sorry for my delay

**Pull request merged**
