### PR TITLE
Update Module.php

### PR DESCRIPTION
**Pull request by Bilge**
Fixed incorrect namespace alias.

### CODE REVIEW

**Comment by RageZBla** [comment]
@Ocramius any chances that get merged, I was about to send the same patch

**Comment by Bilge** [comment]
Ocramius never merges my PRs because he hates me :^)

**Comment by gianarb** [comment]
Hello

at the moment create our aliases..
It is a BC break

**Comment by Bilge** [comment]
@gianarb Could you write that again in English? Google Translate isn't working.

**Comment by gianarb** [comment]
I wrote it without nothing :D you use the label to understand
thanks

**Comment by Bilge** [comment]
I'm sorry but I don't know what you're talking about.

**Comment by gianarb** [comment]
https://en.wiktionary.org/wiki/breaking_change

**Comment by Bilge** [comment]
Would you prefer I added the correct alias *in addition to* the old one, instead of replacing the old one?

**Comment by gianarb** [comment]
No at the moment.
I am working to release a stable version and I will merge this PR during this process

Thanks

**Comment by Bilge** [comment]
OK :+1:

**Comment by alcaeus** [comment]
Fixed in #184.

**Pull request closed without merging**
